# Site settings
title: 'Not Abstract Nonsense' # Your Title
tagline:  An applied mathematician writes. Posts by <a href="https://twitter.com/kgourg">@kgourg</a>. <a href="http://notabstractnonsense.com/atom.xml">RSS feed here.</a>.  

url: https://kgourgou.github.io/myblog/

sidebar_image: /images/cover.jpg

# Build settings
markdown: kramdown
highlighter: rouge
baseurl: /kgourgou.github.io/myblog/ # the subpath of your site, e.g. /blog/
