# Site settings
title: 'Not Abstract Nonsense' # Your Title
tagline:  # A brief tagline for your site
sidebar_image: /images/cover.jpg

# Build settings
markdown: kramdown
highlighter: pygments
baseurl: #notabstractnonsense.com # the subpath of your site, e.g. /blog/
