# Site settings
title: 'Not Abstract Nonsense' # Your Title
tagline:  An applied mathematician writes. Posts by <a href="https://twitter.com/kgourg">@kgourg</a>. <a href="http://notabstractnonsense.com/atom.xml">RSS feed here.</a>.  

#url: notabstractnonsense.com

sidebar_image: /images/cover.jpg

# Build settings
markdown: kramdown
highlighter: pygments
baseurl: /kgourgou.github.io/ # the subpath of your site, e.g. /blog/
